all:
	mkdir -p ~/code/cs/hi
	cd ~/code/cs/hi
	dotnet new console
	dotnet run
	dotnet run --configuration Release
	dotnet run --configuration Debug
	dotnet run -c Debug
	dotnet run -c Release
	dotnet help new
	dotnet new console -h

	time dotnet build -c Release
# Time Elapsed 00:00:05.49
# real    0m5.929s
# user    0m5.025s
# sys     0m0.403s