all:
	mkdir -p ~/code/cs/hi
	cd ~/code/cs/hi
	dotnet new console
	dotnet run
	dotnet run --configuration Release
	dotnet run --configuration Debug
	dotnet run -c Debug
	dotnet run -c Release
	dotnet help new
	dotnet new console -h