[package]
name = "rs103-hash-a-file"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ring = "0.17.0-alpha.11"                     # Safe, fast, small crypto using Rust.